import Plotly from 'plotly.js-basic-dist-min'
import jsPDF from 'jspdf'

export interface PDFStat {
  label: string
  value: string
}

export interface PDFExportOptions {
  divId: string
  title: string
  subtitle?: string
  stats: PDFStat[]
  filename?: string
}

/**
 * Export a report as a landscape A4 PDF:
 *   – Title + subtitle
 *   – Plotly chart (captured via toImage)
 *   – Stats table
 *   – Branded footer
 */
export async function downloadPDF({
  divId,
  title,
  subtitle,
  stats,
  filename = 'report.pdf',
}: PDFExportOptions) {
  const el = document.getElementById(divId)
  if (!el) return

  const imgUrl = await (Plotly as unknown as {
    toImage: (el: HTMLElement, opts: object) => Promise<string>
  }).toImage(el, { format: 'png', width: 1400, height: 700 })

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()   // 297 mm
  const H = doc.internal.pageSize.getHeight()  // 210 mm

  // ── Title ──────────────────────────────────────────────────────────────────
  doc.setFontSize(18)
  doc.setTextColor(20, 20, 40)
  doc.text(title, 14, 18)

  if (subtitle) {
    doc.setFontSize(10)
    doc.setTextColor(90, 90, 110)
    doc.text(subtitle, 14, 25)
  }

  // ── Chart ──────────────────────────────────────────────────────────────────
  const chartTop = subtitle ? 30 : 24
  const chartW   = W - 28         // full width minus margins
  const chartH   = chartW * 0.5   // 2:1 aspect ratio (matches 1400×700 export)
  doc.addImage(imgUrl, 'PNG', 14, chartTop, chartW, chartH)

  // ── Stats ──────────────────────────────────────────────────────────────────
  const statsTop = chartTop + chartH + 6
  const colWidth = 60
  const cols     = Math.floor((W - 28) / colWidth)

  doc.setFontSize(9)
  stats.forEach(({ label, value }, i) => {
    const col = i % cols
    const row = Math.floor(i / cols)
    const x   = 14 + col * colWidth
    const y   = statsTop + row * 9

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(50, 50, 80)
    doc.text(label, x, y)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(30, 30, 30)
    doc.text(value, x, y + 4)
  })

  // ── Footer ─────────────────────────────────────────────────────────────────
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text('Generated by Thotsakan Statistics · Himmapan Lab', 14, H - 6)
  doc.text(new Date().toLocaleDateString(), W - 30, H - 6)

  doc.save(filename)
}
