import Plotly from 'plotly.js-basic-dist-min'
import jsPDF from 'jspdf'
import type { CSVCell } from './exportCSV'
import type { ExportChart } from './exportPNG'

export interface PDFStat { label: string; value: string }
export interface PDFTable { title: string; columns: string[]; rows: CSVCell[][] }
export interface PDFExportOptions {
  title: string
  subtitle?: string
  charts: readonly ExportChart[]
  stats?: PDFStat[]
  tables?: PDFTable[]
  filename?: string
}

const ascii = (value: string) => value
  .replaceAll('α', 'alpha').replaceAll('μ', 'mu').replaceAll('σ', 'sigma')
  .replaceAll('≤', '<=').replaceAll('≥', '>=').replaceAll('≠', '!=').replaceAll('−', '-')
  .replace(/[^\x20-\x7E]/g, '?')

export async function downloadPDF({ title, subtitle, charts, stats = [], tables = [], filename = 'report.pdf' }: PDFExportOptions) {
  if (!charts.length || charts.some((chart) => !chart.element?.isConnected)) {
    throw new Error('Charts are still loading. Try exporting again in a moment.')
  }
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const width = doc.internal.pageSize.getWidth()
  const height = doc.internal.pageSize.getHeight()
  const margin = 14

  doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor(20, 20, 40)
  doc.text(ascii(title), margin, 20)
  if (subtitle) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(90, 90, 110)
    doc.text(ascii(subtitle), margin, 28)
  }
  let y = subtitle ? 40 : 32
  doc.setFontSize(10)
  stats.forEach((stat) => {
    if (y > height - 18) { doc.addPage(); y = 18 }
    doc.setFont('helvetica', 'bold'); doc.setTextColor(50, 50, 80); doc.text(ascii(stat.label), margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(30, 30, 30)
    const lines = doc.splitTextToSize(ascii(stat.value), width - 70)
    doc.text(lines, 60, y)
    y += Math.max(7, lines.length * 5)
  })

  for (const chart of charts) {
    const ratio = chart.element.clientWidth > 0 ? chart.element.clientHeight / chart.element.clientWidth : 0.5
    const image = await (Plotly as unknown as { toImage: (element: HTMLElement, options: object) => Promise<string> })
      .toImage(chart.element, { format: 'png', width: 1400, height: Math.max(500, Math.round(1400 * ratio)) })
    doc.addPage()
    doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.setTextColor(20, 20, 40)
    doc.text(ascii(chart.title || 'Chart'), margin, 16)
    const availableW = width - margin * 2
    const availableH = height - 30
    const imageRatio = Math.max(0.25, ratio)
    let drawW = availableW
    let drawH = drawW * imageRatio
    if (drawH > availableH) { drawH = availableH; drawW = drawH / imageRatio }
    doc.addImage(image, 'PNG', (width - drawW) / 2, 22, drawW, drawH)
  }

  for (const table of tables) {
    doc.addPage()
    y = 18
    const colWidth = (width - margin * 2) / Math.max(1, table.columns.length)
    const header = () => {
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(20, 20, 40)
      doc.text(ascii(table.title), margin, y); y += 8
      doc.setFontSize(8)
      table.columns.forEach((column, index) => doc.text(ascii(column), margin + index * colWidth, y, { maxWidth: colWidth - 2 }))
      y += 7
      doc.setDrawColor(180); doc.line(margin, y - 4, width - margin, y - 4)
    }
    header()
    for (const row of table.rows) {
      const cells = table.columns.map((_, index) => doc.splitTextToSize(ascii(row[index] == null ? '' : String(row[index])), colWidth - 2))
      const rowHeight = Math.max(6, ...cells.map((lines) => lines.length * 4))
      if (y + rowHeight > height - 14) { doc.addPage(); y = 18; header() }
      doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(30, 30, 30)
      cells.forEach((lines, index) => doc.text(lines, margin + index * colWidth, y))
      y += rowHeight
    }
  }

  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page); doc.setFontSize(7); doc.setTextColor(150, 150, 150)
    doc.text('Generated by Thotsakan Statistics - Himmapan Lab', margin, height - 6)
    doc.text(`${page}/${pageCount}`, width - 22, height - 6)
  }
  doc.save(filename)
}
